name:                tabula
version:             0.1.0.0
github:              mbg/tabula
license:             MIT
author:              Michael B. Gale
maintainer:          m.gale@warwick.ac.uk
copyright:           2019 Michael B. Gale

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for the Tabula API
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbg/tabula#readme>

dependencies:
- base
- bytestring
- text
- time
- iso8601-time
- unordered-containers
- aeson
- http-types
- http-client
- http-client-tls
- conduit
- conduit-extra
- http-conduit
- servant
- servant-client
- uuid-types
- mtl
- exceptions

default-extensions:
- OverloadedStrings
- FlexibleInstances
- FlexibleContexts
- DeriveGeneric
- DataKinds
- TypeOperators
- ScopedTypeVariables
- RecordWildCards
- GeneralizedNewtypeDeriving
- OverlappingInstances

library:
  source-dirs: src
