name:                uow-apis
version:             0.2.0.0
github:              mbg/uow-apis
license:             MIT
author:              Michael B. Gale
maintainer:          m.gale@warwick.ac.uk
copyright:           2019 Michael B. Gale

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for UoW APIs
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbg/uow-apis#readme>

dependencies:
- base
- bytestring
- text
- time
- iso8601-time
- containers
- unordered-containers
- aeson
- xeno
- xml-types
- xml-conduit
- feed
- http-types
- http-client
- http-client-tls
- http-media
- mime-types
- conduit
- conduit-extra
- http-conduit
- servant
- servant-client
- uuid-types
- mtl
- exceptions

default-extensions:
- OverloadedStrings
- FlexibleInstances
- FlexibleContexts
- DeriveGeneric
- DataKinds
- TypeOperators
- ScopedTypeVariables
- RecordWildCards
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverlappingInstances

library:
  source-dirs: src
