name:                uow-apis
version:             0.4.2.0
github:              mbg/uow-apis
license:             MIT
author:              Michael B. Gale <m.gale@warwick.ac.uk>, Oscar Harris <Oscar.Harris@warwick.ac.uk>
maintainer:          Michael B. Gale <m.gale@warwick.ac.uk>
copyright:           Copyright (c) Michael B. Gale

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for UoW APIs
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbg/uow-apis#readme>

flags:
  build-exe:
    manual: true 
    default: false

dependencies:
- base
- bytestring
- data-default
- text
- time
- iso8601-time
- containers
- unordered-containers
- hashable
- aeson
- xeno
- xml-types
- xml-conduit
- feed
- http-types
- http-client
- http-client-tls
- http-media
- mime-types
- conduit
- conduit-extra
- http-conduit
- servant
- servant-client
- uuid-types
- mtl
- exceptions
- filepath
- http-api-data
- servant-multipart
- uuid

default-extensions:
- OverloadedStrings
- FlexibleInstances
- FlexibleContexts
- DeriveGeneric
- DataKinds
- TypeOperators
- ScopedTypeVariables
- RecordWildCards
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror=missing-fields

executables:
  uow-util:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    dependencies:
      - uow-apis
      - extra
      - optparse-applicative
      - directory
      - ascii-progress
      - yaml
      - filepattern
    default-extensions:
      - LambdaCase
    when:
      condition: flag(build-exe)
      then:
        buildable: true 
      else: 
        buildable: false