version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-13.26
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - tabula-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Build
          command: stack build
      - save_cache:
          name: Cache Dependencies
          key: tabula-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
            - "~/.stack"
      #- store_artifacts: # upload build artifact for display in CircleCI
      #    path: ~/.local/bin/circleci-demo-haskell-exe
      #    destination: circleci-demo-haskell-exe
